default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['ENGLISH_CAMP_DATABASE_USERNAME'] %>
  password: <%= ENV['ENGLISH_CAMP_DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: english_camp_development

test:
  <<: *default
  database: english_camp_test

production:
  <<: *default
  database: english_camp_production
  username: <%= ENV['ENGLISH_CAMP_DATABASE_USERNAME'] %>
  password: <%= ENV['ENGLISH_CAMP_DATABASE_PASSWORD'] %>